// <auto-generated />
namespace CalCalTracker.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class initialise : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initialise));
        
        string IMigrationMetadata.Id
        {
            get { return "201712031833302_initialise"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
